# Generated by Django 3.1.6 on 2021-02-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usersemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersEmail',
        ),
    ]
